import p from "../package.json" assert { type: "json" };
import path from "path";
import fs from "fs/promises";

const packageVersion = p.version;

const getCurrentScriptFilepath = () => {
  const url = new URL(import.meta.url);
  return url.pathname;
};

const outputScriptPath = path.join(path.dirname(getCurrentScriptFilepath()), "../src/client/version.gen.ts");

const scriptContents = `// This file is auto-generated by scripts/updateVersion.mjs
// Do not edit this file directly
export const SDK_VERSION = "${packageVersion}";
`;

fs.writeFile(outputScriptPath, scriptContents, { encoding: "utf-8" });
